USE sakila;

#1 List the number of films per category.

SELECT category.name AS category_name, 
COUNT(film_id) AS film_count
FROM film #table 1
INNER JOIN film_category  #table2
USING(film_id)	#key

INNER JOIN category #table 3
USING(category_id)	#key
GROUP BY category.name;


#2 Retrieve the store ID, city, and country for each store.
select store_id, city, country
from store
inner join address
using(address_id)
inner join city
using(city_id)
inner join country
using(country_id);

#3 Calculate the total revenue generated by each store in dollars.
select store_id, sum(amount) AS total_revenue
from payment
inner join staff
using(staff_id)
group by store_id;

#4 Determine the average running time of films for each category.
select name as category_name , avg(length) as avg_time
from film
inner join film_category
using(film_id)
inner join category
using(category_id)
group by category.name;

